# Render configuration file for FastAPI and MySQL

services:
  - type: web
    name: fastapi-app
    env: python
    region: ohio  # Choose your preferred region
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_HOST
        fromDatabase:
          name: mysql-db
          property: host
      - key: DATABASE_USER
        fromDatabase:
          name: mysql-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: mysql-db
          property: password
      - key: DATABASE_NAME
        fromDatabase:
          name: mysql-db
          property: database
    healthCheckPath: /docs  # Health check endpoint (FastAPI Swagger UI)

databases:
  - name: mysql-db
    databaseName: liver_disease_db
    user: root
    region: ohio  # Choose your preferred region
    plan: free  # Use "free" for testing or "starter" for production
